### PR TITLE
Fix the docker build: Install git in the docker image builder

### LINKED ISSUE #244: Docker build is broken
The docker build is broken, so 0.10.0 has not received a Docker build.

### PR DESCRIPTION
**Pull request by reivilibre**
Fixes #244 .

### CODE REVIEW

**Comment by clokep** [comment]
@reivilibre Needs a newsfile, but seems OK.

File: docker/Dockerfile [hunk 1]
```diff
@@ -11,11 +11,9 @@
 ###
 FROM python:3.7-slim as builder
 
-# build things which have slow build steps, before we copy sygnal, so that
-# the layer can be cached.
-#
-# (we really just care about caching a wheel here, as the "pip install" below
-# will install them again.)
+# we need git for installing Sygnal, because the package version is obtained
+# from the state of the git repository
```
Comment (clokep) [inline docker/Dockerfile:15]:
```suggestion
# Install git, Sygnal uses it to obtain the package version from the state of the git repository.
```

File: changelog.d/246.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix the docker image build from failing due to `git` not being installed.
```
Comment (clokep) [inline changelog.d/246.bugfix:1]: Please use a `.docker` extension and mention that this broke in v0.10.0

**Review by clokep — CHANGES_REQUESTED** [review]

**Review by clokep — APPROVED** [review]
LGTM!
